generator {
  kafka {
    bootstrap-servers = "localhost:9092"
    bootstrap-servers = ${?GENERATOR_KAFKA_BOOTSTRAP_SERVERS}

    topic = "transactions"
    topic = ${?GENERATOR_KAFKA_TOPIC}

    client-id-prefix = "event-generator"
    client-id-prefix = ${?GENERATOR_KAFKA_CLIENT_ID_PREFIX}

    acks = "all"

    linger-ms = 20
    linger-ms = ${?GENERATOR_KAFKA_LINGER_MS}
  }

  simulation {
    target-rate-per-second = 10
    target-rate-per-second = ${?GENERATOR_SIMULATION_TARGET_RATE_PER_SECOND}

    metrics-interval = "10s"
    metrics-interval = ${?GENERATOR_SIMULATION_METRICS_INTERVAL}
  }
}