/*
 * This source file was generated by the Gradle 'init' task
 */
package com.pipeline.generator
import com.pipeline.generator.generator.TransactionGenerator
import kotlinx.serialization.json.Json
import org.apache.kafka.clients.producer.KafkaProducer
import org.apache.kafka.clients.producer.ProducerConfig
import org.apache.kafka.clients.producer.ProducerRecord
import org.apache.kafka.common.serialization.StringSerializer

const val BOOTSTRAP_SERVERS = "localhost:9092"
const val TOPIC = "transactions"
const val RECORDS_TO_SEND = 10

fun main() {
    val config = mapOf(
        ProducerConfig.BOOTSTRAP_SERVERS_CONFIG to BOOTSTRAP_SERVERS,
        ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG to StringSerializer::class.java.name,
        ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG to StringSerializer::class.java.name,
        ProducerConfig.CLIENT_ID_CONFIG to "event-generator",
        ProducerConfig.ACKS_CONFIG to "all",
    )

    KafkaProducer<String, String>(config).use { producer ->
        repeat(RECORDS_TO_SEND) { index ->
            val transaction = TransactionGenerator.random()
            val json = Json.encodeToString(transaction)

            val record = ProducerRecord(TOPIC, transaction.cardId, json)
            val metadata = producer.send(record).get()

            println(
                "[$index] ${transaction.cardId} " +
                        "$${transaction.amountCents / 100.0} @ ${transaction.merchant} " +
                        "-> partition=${metadata.partition()}, offset=${metadata.offset()}",
            )
        }

    }

    println("Sent $RECORDS_TO_SEND transactions. Producer closed cleanly.")
}
