/*
 * This source file was generated by the Gradle 'init' task
 */
package com.pipeline.generator
import org.apache.kafka.clients.producer.KafkaProducer
import org.apache.kafka.clients.producer.ProducerConfig
import org.apache.kafka.clients.producer.ProducerRecord
import org.apache.kafka.common.serialization.StringSerializer

const val BOOTSTRAP_SERVERS = "localhost:9092"
const val TOPIC = "transactions"

fun main() {
    val config = mapOf(
        ProducerConfig.BOOTSTRAP_SERVERS_CONFIG to BOOTSTRAP_SERVERS,
        ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG to StringSerializer::class.java.name,
        ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG to StringSerializer::class.java.name,
        ProducerConfig.CLIENT_ID_CONFIG to "event-generator",
        ProducerConfig.ACKS_CONFIG to "all",
    )

    KafkaProducer<String, String>(config).use { producer ->
        val key = "card-1234"
        val value = """{"card":"1234", "amount":13.5", "merchant":"coffee shop"}"""

        val record = ProducerRecord(TOPIC, key,value)
        println("Sending 1 record to topic $TOPIC ....")
        val metadata = producer.send(record).get()

        println(
            "Delivered -> partition=${metadata.partition()}, " +
                    "offset=${metadata.offset()}, " +
                    "timestamp=${metadata.timestamp()}",
        )
    }

    println("Producer closed cleanly.")
}
